services:
    rabbitmq:
        ports:
            - "${INTEGRATION_RABBITMQ_AMQP_PORT:-5673}:5672"

    app:
        environment:
            SENDGRID_ENABLED: "false"
            RABBITMQ_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/%2F"
