CREATE TABLE IF NOT EXISTS users (
    id CHAR(36) PRIMARY KEY,
    email VARCHAR(254) UNIQUE NOT NULL,
    firstName VARCHAR(80),
    lastName VARCHAR(80),
    gdprConsent BOOLEAN NOT NULL DEFAULT FALSE,
    companyId CHAR(36) NULL,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mail_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId CHAR(36),
    templateId VARCHAR(100),
    status ENUM('SENT', 'BOUNCED', 'FAILED') DEFAULT 'SENT',
    sentAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id)
);
